### ISSUE TITLE
Some science issues

### ISSUE THREAD

**Issue by Very-Soft** [VOREStation/VOREStation#2395]
#### ACCESS
Coming back to science after a bit of a break I've found a few things have changed, that don't make much sense:

So, Roboticists no longer have access to R&D. (Which is needed for when there's no other science around and they want to actually do their job)

Xenobiologists no longer have access to Xenobiology
I've also seen some scientists unable to access Robotics, though I'm not 100% sure on what ranks can and can't.

All of science should have access to robotics, in case synths need to be resleeved. Obviously this job should fall to roboticists first, but with the more limited job slots for robotics, it needlessly restricts a vital station function to two people, who often end up off lewding somewhere.

#### RESEARCH

I'm not sure if it was intended or not, possibly something from a polaris sync, but getting illegal research up high enough to get the translocator seems to rely super heavily on trashpile RNG, when science already rarely has the materials to make it to begin with, as the guns from chameleon kits have been nerfed to 4 illegal tech.

That I know of, the only things that give enough illegal tech now are the jammers, which are actually pretty rare now. And of course, the trashpile translocator. But, good luck actually getting that.

**Comment by Gearshy** [comment]
Missing access has been an issue since the last major release batch, and should be fixed in the next Polaris sync. The actual door locks will still be wonky, but at least they'll only be secretly wonky.

**Comment by SpadesNeil** [comment]
The access issue is a map issue, not an update issue. The update just broke the ID cards' expanded access. The access to the actual rooms is still incorrect, it just never got noticed until now.

**Comment by Arokha** [comment]
Pretty sure this is fixed
