### ISSUE TITLE
Solar panels in backpack

### ISSUE THREAD

**Issue by Dr0ppy** [VOREStation/VOREStation#449]
#### Brief description of the issue

If you put a solar panel in a backpack it gets automatically wrencehd, and when you wrench ityou keep unwrenching it, but it immideately re-wrenches.
#### What you expected to happen

To be able to get the assembly out of the backpack
#### What actually happened

It gets anchored in teh backpack, and you cant get it out
#### Steps to reproduce

put assembly in backpack
#### Additional info:
- **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
  same as the cryo bug
- **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Dr0ppy** [comment]
After further testing, putting a glass panel on it, it spawns on teh ground
then crowbar it and you can move it, but the icon is stuck on your HUD while it disepars from the backpack

**Comment by SpadesNeil** [comment]
This should be fixed now.

**Comment by Eearslya** [comment]
Confirmed still broken as of b1b0f289387b7bb0585f63f02d3617bf931bc847.

**Comment by Eearslya** [comment]
Submitted to Polaris https://github.com/PolarisSS13/Polaris/pull/2626

**Comment by Arokha** [comment]
Was fixed upstrea with @Eearslya 's thing.
