### ISSUE TITLE
Research Cyborg sheet loader can not load Protolathe or circuit imprinter

### ISSUE THREAD

**Issue by DeepIndigo** [VOREStation/VOREStation#728]
#### 1. Be research cyborg
         2. Pick up sheets into sheet loader
         3. Try to load them into Protolathe or circuit imprinter
         4. Get "You can't add this component to the protolathe/circuit imprinter!" message.

#### Additional info:
 - **Server Revision**: Current

**Comment by SpadesNeil** [comment]
I thought this got fixed by Polaris lately.

**Comment by SpadesNeil** [comment]
Needs re-testing after update.

**Comment by DeepIndigo** [comment]
Tested just now, still doesn't work. Time is 16:06 11.Dec.2016 pacific US/Canada time.

**Comment by Heroman3003** [comment]
It has been fixed at some point. Ancient issue, but still should be closed.

**Comment by Screemonster** [comment]
Closing issue as per above, open a new one if this turns into a problem again etc.
